import type { Metadata } from 'next';
import { Montserrat, Raleway } from 'next/font/google';
import './globals.css';
import type { NextFontWithVariable } from 'next/dist/compiled/@next/font';
import type { JSX } from 'react';

import { cn } from '@/lib/utils';

const montserratHeading: NextFontWithVariable = Montserrat({
  subsets: ['latin'],
  variable: '--font-heading',
});

const raleway: NextFontWithVariable = Raleway({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'BeStats',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        raleway.variable,
        montserratHeading.variable,
      )}
    >
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  );
}
