import Link from 'next/link';
import type { JSX } from 'react';

import { formatNumber } from '@/lib/format';
import { cn } from '@/lib/utils';

/**
 * One tab: where it goes, the word it wears, whether it is the open one, and
 * the count beside the word — `null` when that count is Unanswered, and left
 * out while it is still being asked for, since the tabs are the fallback the
 * counts stream into and a dash there would report waiting as a failure.
 */
type LinkTab = {
  href: string;
  label: string;
  selected: boolean;
  tally?: number | null;
};

/**
 * The count a tab wears. On the search tabs it is every Match TMDB reported
 * for that Kind, not the first page of them; on the lists it is every Watch
 * Record in that state. Either way the closed tab admits what is waiting
 * behind it.
 *
 * An Unanswered count wears a dash instead. Nobody said how many, and a `0`
 * there would report a failure as an absence — the same mistake as rendering
 * a placeholder Fact.
 */
const Tally = ({ tally }: { tally: number | null }): JSX.Element =>
  tally === null ? (
    <span className='ml-2 font-normal opacity-40'>
      <span aria-hidden='true'>—</span>
      <span className='sr-only'>unanswered</span>
    </span>
  ) : (
    <span className='ml-2 font-normal tabular-nums opacity-60'>
      {formatNumber(tally)}
    </span>
  );

/**
 * Tabs drawn as links rather than as tab state. The selected one belongs in
 * the address, so a search or a list can be shared as the page the sender
 * meant; Base UI's Tabs would hold that choice in the client and leave the
 * URL saying something else.
 *
 * The classes below mirror `TabsTrigger` in `components/ui/tabs.tsx` so these
 * and the trending tabs read as one control, and they are copied because they
 * cannot be shared: that file is generated by shadcn and holds the string
 * inline, and lifting it out would mean editing a file we keep in its
 * generated shape. Even exported it would not fit whole — Base UI marks the
 * open tab with `data-active`, which a `<Link>` never carries, so the selected
 * state is rewritten here against `aria-current`, and what a trigger affords
 * and a link does not (`disabled:`, the vertical orientation, the icon slots)
 * is deliberately left behind.
 *
 * So this is a mirror with a seam, not a copy, and nothing enforces it:
 * restyling the trending tabs leaves these where they are. Re-read
 * `TabsTrigger` and carry the difference across by hand. It is mirrored
 * once, here, and both the search tabs and the lists' tabs are built on it.
 * — `docs/adr/0004-search-is-two-searches.md`
 *
 * `replace` is the caller's: a toggle within one search is a step within
 * that search, and pushes nothing; the two lists are two pages, and do.
 */
const LinkTabs = ({
  label,
  tabs,
  replace = false,
}: {
  label: string;
  tabs: readonly LinkTab[];
  replace?: boolean;
}): JSX.Element => (
  <nav
    aria-label={label}
    className='mx-auto inline-flex h-10 w-fit items-center justify-center bg-muted p-1'
  >
    {tabs.map((tab) => (
      <Link
        key={tab.href}
        href={tab.href}
        replace={replace}
        aria-current={tab.selected ? 'page' : undefined}
        className={cn(
          'inline-flex h-[calc(100%-1px)] items-center justify-center border border-transparent px-4 py-1.5 font-semibold text-foreground/60 text-xs uppercase tracking-wider transition-colors hover:text-foreground focus-visible:outline-1 focus-visible:outline-ring',
          tab.selected &&
            'bg-background text-foreground dark:border-input dark:bg-input/30',
        )}
      >
        {tab.label}
        {tab.tally !== undefined ? <Tally tally={tab.tally} /> : null}
      </Link>
    ))}
  </nav>
);

export { LinkTabs };
export type { LinkTab };
