import Link from 'next/link';
import type { JSX } from 'react';

import { formatNumber } from '@/lib/format';
import { cn } from '@/lib/utils';

/**
 * One tab: where it goes, the word it wears, whether it is the open one, and
 * the count beside the word — `null` when that count is Unanswered, and left
 * out while it is still being asked for, since the tabs are the fallback the
 * counts stream into and a dash there would report waiting as a failure.
 */
type LinkTab = {
  href: string;
  label: string;
  selected: boolean;
  tally?: number | null;
};

/**
 * The count a tab wears, which is one Kind's either way: on the search tabs
 * every Match TMDB reported for that Kind, not the first page of them; on a
 * list every Watch Record of that Kind in the state the list shows. Either
 * way the closed tab admits what is waiting behind it.
 *
 * An Unanswered count wears a dash instead. Nobody said how many, and a `0`
 * there would report a failure as an absence — the same mistake as rendering
 * a placeholder Fact.
 */
const Tally = ({ tally }: { tally: number | null }): JSX.Element =>
  tally === null ? (
    <span className='ml-2 font-normal opacity-40'>
      <span aria-hidden='true'>—</span>
      <span className='sr-only'>unanswered</span>
    </span>
  ) : (
    <span className='ml-2 font-normal tabular-nums opacity-60'>
      {formatNumber(tally)}
    </span>
  );

/**
 * Tabs drawn as links rather than as tab state. The selected one belongs in
 * the address, so a search or a list can be shared as the page the sender
 * meant; Base UI's Tabs would hold that choice in the client and leave the
 * URL saying something else.
 *
 * The classes below mirror `TabsTrigger` in `components/ui/tabs.tsx` so these
 * and the trending tabs read as one control, and they are copied because they
 * cannot be shared: that file is generated by shadcn and holds the string
 * inline, and lifting it out would mean editing a file we keep in its
 * generated shape. Even exported it would not fit whole — Base UI marks the
 * open tab with `data-active`, which a `<Link>` never carries, so the selected
 * state is rewritten here against `aria-current`, and what a trigger affords
 * and a link does not (`disabled:`, the vertical orientation, the icon slots)
 * is deliberately left behind.
 *
 * So this is a mirror with a seam, not a copy, and nothing enforces it:
 * restyling the trending tabs leaves these where they are. Re-read
 * `TabsTrigger` and carry the difference across by hand. It is mirrored
 * once, here, and both the search tabs and the lists' tabs are built on it.
 * `whitespace-nowrap` is one such difference, carried across late: without
 * it a tab whose word and count outgrow the row wrapped inside a fixed
 * `h-10` and was cut off rather than pushing anything.
 * — `docs/adr/0004-search-is-two-searches.md`
 *
 * The padding narrows below `sm:` because these two tabs wear counts, and a
 * count is as wide as the number in it. The widest row either caller draws is
 * a search whose two totals are five figures — `/search?q=a` answers 10,000
 * for both — and it measures 268px at `px-2.5` and 292px at `px-4`, against
 * the 288px a 320px screen leaves inside the page's `p-4`. So the wide
 * padding is 4px more than there is, and the narrow one is what fits. The
 * tabs are what give, since a count that cannot be read is the thing the tab
 * is for. A list's tallies are Watch Record counts and its row is narrower.
 *
 * The trending tabs wear no count and so did not need it, but they carry the
 * same `px-2.5 sm:px-4` at their call site in `app/page.tsx`: the mirror is
 * for reading as one control, and two tab sets that disagree about their
 * padding on the width this was written for would not. It is passed as a
 * `className` there rather than changed in `TabsTrigger`, which stays in its
 * generated shape. This is the seam again — restyle one, carry it to the
 * other.
 *
 * `replace` is the caller's, and both callers pass it: a Kind is a step
 * within one search or one list rather than a page of either. What is a page
 * still pushes — the `Previous` and `Next` below a list are ordinary links.
 */
const LinkTabs = ({
  label,
  tabs,
  replace = false,
}: {
  label: string;
  tabs: readonly LinkTab[];
  replace?: boolean;
}): JSX.Element => (
  <nav
    aria-label={label}
    className='mx-auto inline-flex h-10 w-fit items-center justify-center bg-muted p-1'
  >
    {tabs.map((tab) => (
      <Link
        key={tab.href}
        href={tab.href}
        replace={replace}
        aria-current={tab.selected ? 'page' : undefined}
        className={cn(
          'inline-flex h-[calc(100%-1px)] items-center justify-center whitespace-nowrap border border-transparent px-2.5 py-1.5 font-semibold text-foreground/60 text-xs uppercase tracking-wider transition-colors hover:text-foreground focus-visible:outline-1 focus-visible:outline-ring sm:px-4',
          tab.selected &&
            'bg-background text-foreground dark:border-input dark:bg-input/30',
        )}
      >
        {tab.label}
        {tab.tally !== undefined ? <Tally tally={tab.tally} /> : null}
      </Link>
    ))}
  </nav>
);

export { LinkTabs };
export type { LinkTab };
