import Link from 'next/link';
import type { JSX } from 'react';

import { formatNumber } from '@/lib/format';
import {
  KIND_WORDS,
  KINDS,
  type Kind,
  type Matches,
  type Search,
} from '@/lib/media';
import { cn } from '@/lib/utils';

/**
 * The count a tab wears: every Match TMDB reported for that Kind, not the
 * first page of them, so the closed tab admits what is waiting behind it.
 *
 * An unanswered Kind wears a dash instead. TMDB never said how many matched,
 * and a `0` there would report a failure as an absence — the same mistake as
 * rendering a placeholder Fact.
 */
const Tally = ({ matches }: { matches: Matches | null }): JSX.Element =>
  matches === null ? (
    <span className='ml-2 font-normal opacity-40'>
      <span aria-hidden='true'>—</span>
      <span className='sr-only'>unanswered</span>
    </span>
  ) : (
    <span className='ml-2 font-normal tabular-nums opacity-60'>
      {formatNumber(matches.total)}
    </span>
  );

/**
 * Tabs drawn as links rather than as tab state. The selected Kind belongs in
 * the address, so a search can be shared as the list the sender meant; Base
 * UI's Tabs would hold that choice in the client and leave the URL saying
 * something else.
 *
 * The classes below mirror `TabsTrigger` in `components/ui/tabs.tsx` so these
 * and the trending tabs read as one control, and they are copied because they
 * cannot be shared: that file is generated by shadcn and holds the string
 * inline, and lifting it out would mean editing a file we keep in its
 * generated shape. Even exported it would not fit whole — Base UI marks the
 * open tab with `data-active`, which a `<Link>` never carries, so the selected
 * state is rewritten here against `aria-current`, and what a trigger affords
 * and a link does not (`disabled:`, the vertical orientation, the icon slots)
 * is deliberately left behind.
 *
 * So this is a mirror with a seam, not a copy, and nothing enforces it:
 * restyling the trending tabs leaves these where they are. Re-read
 * `TabsTrigger` and carry the difference across by hand.
 *
 * They replace rather than push, so the page's `Back` returns to trending
 * rather than to whichever tab was open before.
 *
 * Both Kinds' Matches are already fetched, so both counts are shown here: a
 * Query's best answer can sit behind the closed tab, and the count is the only
 * thing that says so.
 * — `docs/adr/0004-search-is-two-searches.md`
 */
const KindTabs = ({
  query,
  selected,
  search,
}: {
  query: string;
  selected: Kind;
  search: Search;
}): JSX.Element => {
  return (
    // Labelled with the two words the reader sees rather than with "Kind":
    // Kind is the glossary's word for the distinction, not a word a visitor
    // hearing this nav announced would recognise.
    <nav
      aria-label='Shows or movies'
      className='mx-auto inline-flex h-10 w-fit items-center justify-center bg-muted p-1'
    >
      {KINDS.map((kind) => (
        <Link
          key={kind}
          href={`/search?q=${encodeURIComponent(query)}&kind=${kind}`}
          replace
          aria-current={kind === selected ? 'page' : undefined}
          className={cn(
            'inline-flex h-[calc(100%-1px)] items-center justify-center border border-transparent px-4 py-1.5 font-semibold text-foreground/60 text-xs uppercase tracking-wider transition-colors hover:text-foreground focus-visible:outline-1 focus-visible:outline-ring',
            kind === selected &&
              'bg-background text-foreground dark:border-input dark:bg-input/30',
          )}
        >
          {KIND_WORDS[kind].label}
          <Tally matches={search[kind]} />
        </Link>
      ))}
    </nav>
  );
};

export { KindTabs };
